#version: '3'

volumes:
  student-app-db:

services:
  student-app-db:
    image: 'postgres:latest'
    container_name: 'student-app-db'
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    volumes:
      - student-app-db:/var/lib/postgresql/data